name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.25

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test
        run: make test

      - name: Package
        run: make package

#      - name: Docker push
#        env:
#          DOCKER_LOGIN: tidwall
#          DOCKER_USER: tile38
#          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#        run: ./scripts/docker-push.sh

      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker push to GHCR
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          GITHUB_USER: ${{ github.repository_owner }}
        run: |
          bash ./scripts/ghcr-push.sh
